export const tables = [
  {
    id: 1,
    number: 1,
    capacity: 4,
    price: 100,
    speciality: "Window View",
    booked: false,
    charges: 10,
  },
  {
    id: 2,
    number: 2,
    capacity: 6,
    price: 120,
    speciality: "Quiet Corner",
    booked: true,
    charges: 0,
  },
  {
    id: 3,
    number: 3,
    capacity: 4,
    price: 100,
    speciality: "Window View",
    booked: true,
    charges: 10,
  },
  {
    id: 4,
    number: 4,
    capacity: 6,
    price: 120,
    speciality: "Quiet Corner",
    booked: true,
    charges: 10,
  },
  {
    id: 5,
    number: 5,
    capacity: 4,
    price: 100,
    speciality: "None",
    booked: false,
    charges: 10,
  },
  {
    id: 6,
    number: 6,
    capacity: 6,
    price: 120,
    speciality: "Quiet Corner",
    booked: false,
    charges: 5,
  },
  {
    id: 7,
    number: 7,
    capacity: 6,
    price: 120,
    speciality: "Quiet Corner",
    booked: true,
    charges: 10,
  },
  {
    id: 8,
    number: 8,
    capacity: 4,
    price: 100,
    speciality: "Window View",
    booked: false,
    charges: 0,
  },
  {
    id: 9,
    number: 9,
    capacity: 6,
    price: 120,
    speciality: "Quiet Corner",
    booked: true,
    charges: 10,
  },
];


